# -*- coding: utf-8 -*-
"""AI-Powered Data Governance and Insight Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxdUZfLr111J-hkXSGWc6wMsw61Xf1gz
"""

import pandas as pd
import streamlit as st
import torch
from transformers import pipeline
import os

# --- Hugging Face Integration ---
@st.cache_resource
def load_ai_model():
    """
    Loads a text-generation pipeline.
    Using 'Mistral-7B-Instruct' or 'Phi-3' for high performance-to-size ratio.
    """
    model_id = "microsoft/Phi-3-mini-4k-instruct" # Lightweight and powerful for local use
    pipe = pipeline(
        "text-generation",
        model=model_id,
        model_kwargs={"torch_dtype": torch.bfloat16 if torch.cuda.is_available() else torch.float32},
        device_map="auto"
    )
    return pipe

def query_local_ai(prompt, pipe):
    messages = [{"role": "user", "content": prompt}]
    generation_args = {
        "max_new_tokens": 500,
        "return_full_text": False,
        "temperature": 0.7,
        "do_sample": True,
    }
    output = pipe(messages, **generation_args)
    return output[0]['generated_text']

# --- Data Logic ---
class TransformationEngine:
    def __init__(self, df):
        self.df = df

    def check_integrity(self):
        return {
            "Nulls": self.df.isnull().sum().to_dict(),
            "Duplicates": int(self.df.duplicated().sum()),
            "Types": self.df.dtypes.astype(str).to_dict()
        }

    def apply_business_rules(self):
        # 1. Customer Health Score (0-100)
        self.df['Health_Score'] = (
            (self.df['purchase_count'] * 0.4) +
            (self.df['avg_order_value'] * 0.4) +
            (self.df['retention_days'] * 0.2)
        ).clip(0, 100)

        # 2. Churn Risk Logic
        self.df['Risk_Level'] = self.df['Health_Score'].apply(
            lambda x: 'High' if x < 30 else ('Medium' if x < 70 else 'Low')
        )

        # 3. Value Segmentation
        self.df['Segment'] = pd.qcut(self.df['avg_order_value'], 3, labels=["Budget", "Mid-Tier", "VIP"])
        return self.df