# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CBGKLZOlUo4GVPXN176CUhKO_7HqLrA
"""

st.set_page_config(page_title="Local AI Data Pipeline", layout="wide")
st.title("🛡️ AI-Powered Data Governance (Hugging Face Edition)")

# Sidebar for local model status
st.sidebar.header("Model Status")
with st.spinner("Loading Local LLM..."):
    llm_pipe = load_ai_model()
st.sidebar.success("Model Loaded Successfully")

uploaded_file = st.file_uploader("Upload CSV", type="csv")

if uploaded_file:
    raw_df = pd.read_csv(uploaded_file)
    engine = TransformationEngine(raw_df)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📋 Data Integrity Report")
        st.json(engine.check_integrity())

    with col2:
        st.subheader("⚙️ Applied Transformations")
        processed_df = engine.apply_business_rules()
        st.dataframe(processed_df.head(5))

    st.divider()

    if st.button("Generate AI Documentation & Insights"):
        # Documentation Prompt
        code_context = """
        Rule 1: Health_Score = (purchase_count*0.4 + avg_order_value*0.4 + retention_days*0.2)
        Rule 2: Risk_Level = High if Health_Score < 30 else Medium/Low
        Rule 3: Segment = Tertile split based on average order value
        """

        with st.spinner("Local AI is analyzing the pipeline..."):
            brd = query_local_ai(f"Write a Business Requirements Document (BRD) for this logic: {code_context}", llm_pipe)
            stats = processed_df.describe().to_string()
            strategy = query_local_ai(f"Give 3 CEO recommendations based on these stats: {stats}", llm_pipe)

        st.subheader("📄 Automated Business Requirements")
        st.info(brd)

        st.subheader("🎯 Strategic Recommendations")
        st.success(strategy)